// Automatically generated by astro-icon
// d9099b077707331aa4933ef80eafd46900fcbd104d7f115460eaff90cbed6cdb

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "biceps"
		| "bulb"
		| "edit"
		| "error"
		| "external-link"
		| "info"
		| "lighthouse"
		| "mdx"
		| "moon"
		| "opensource"
		| "share"
		| "signal"
		| "success"
		| "sun"
		| "warning"
		| "write";
}